// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFtY4GoIDygVSIHLEiEP3V31c4egWSYT4',
    appId: '1:634102915421:web:e98f08ca66bebc7b4208b4',
    messagingSenderId: '634102915421',
    projectId: 'tickfair-connect-ff20d',
    authDomain: 'tickfair-connect-ff20d.firebaseapp.com',
    storageBucket: 'tickfair-connect-ff20d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUwwbT9HUx_tAReI895xsbsJLavtQ44s0',
    appId: '1:634102915421:android:863a134cd6c4a39d4208b4',
    messagingSenderId: '634102915421',
    projectId: 'tickfair-connect-ff20d',
    storageBucket: 'tickfair-connect-ff20d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJAWXIRPW22uKBbs6AGSVFr4ELROpSUvc',
    appId: '1:634102915421:ios:940dba178d62acb24208b4',
    messagingSenderId: '634102915421',
    projectId: 'tickfair-connect-ff20d',
    storageBucket: 'tickfair-connect-ff20d.firebasestorage.app',
    iosClientId: '634102915421-bg5cesfc54ia77omb57253cm8f8olhil.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickfairConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJAWXIRPW22uKBbs6AGSVFr4ELROpSUvc',
    appId: '1:634102915421:ios:940dba178d62acb24208b4',
    messagingSenderId: '634102915421',
    projectId: 'tickfair-connect-ff20d',
    storageBucket: 'tickfair-connect-ff20d.firebasestorage.app',
    iosClientId: '634102915421-bg5cesfc54ia77omb57253cm8f8olhil.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickfairConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFtY4GoIDygVSIHLEiEP3V31c4egWSYT4',
    appId: '1:634102915421:web:785f4f613d6255054208b4',
    messagingSenderId: '634102915421',
    projectId: 'tickfair-connect-ff20d',
    authDomain: 'tickfair-connect-ff20d.firebaseapp.com',
    storageBucket: 'tickfair-connect-ff20d.firebasestorage.app',
  );
}
