// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9TcMOIw67gSzZ0ZjdidivYWsCUfc5uj4',
    appId: '1:654837117683:web:538f23ffd48991b6f6fd86',
    messagingSenderId: '654837117683',
    projectId: 'tickfair-connect-b00d8',
    authDomain: 'tickfair-connect-b00d8.firebaseapp.com',
    storageBucket: 'tickfair-connect-b00d8.firebasestorage.app',
    measurementId: 'G-JZR9WL161W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFxOKia0mmmcYClJmr0kE5p4eEdlrc1s',
    appId: '1:654837117683:android:6cec3646b3750a15f6fd86',
    messagingSenderId: '654837117683',
    projectId: 'tickfair-connect-b00d8',
    storageBucket: 'tickfair-connect-b00d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABPFWEIgVzHwZ9m4W78s_GTXChJLfYfrY',
    appId: '1:654837117683:ios:cf2ed50f27d65a6ff6fd86',
    messagingSenderId: '654837117683',
    projectId: 'tickfair-connect-b00d8',
    storageBucket: 'tickfair-connect-b00d8.firebasestorage.app',
    iosClientId: '654837117683-cjo78gclavn4ef3ci5tbkf9oncivs4rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickfairConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABPFWEIgVzHwZ9m4W78s_GTXChJLfYfrY',
    appId: '1:654837117683:ios:cf2ed50f27d65a6ff6fd86',
    messagingSenderId: '654837117683',
    projectId: 'tickfair-connect-b00d8',
    storageBucket: 'tickfair-connect-b00d8.firebasestorage.app',
    iosClientId: '654837117683-cjo78gclavn4ef3ci5tbkf9oncivs4rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickfairConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9TcMOIw67gSzZ0ZjdidivYWsCUfc5uj4',
    appId: '1:654837117683:web:94ffafd7fdbd2df6f6fd86',
    messagingSenderId: '654837117683',
    projectId: 'tickfair-connect-b00d8',
    authDomain: 'tickfair-connect-b00d8.firebaseapp.com',
    storageBucket: 'tickfair-connect-b00d8.firebasestorage.app',
    measurementId: 'G-1D7L3952LB',
  );
}
